name: Build Docker Image

on:
  push:
    branches: ["main"]
    paths:
      - posts/**
      - Dockerfile
      - .dockerignore
      - static/**
      - templates/**
      - requirements.txt
      - app.py
  pull_request:
    branches: ["main"]
    paths:
      - posts/**
      - Dockerfile
      - .dockerignore
      - static/**
      - templates/**
      - requirements.txt
      - app.py
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag dec3ntraliz3d/blog:latest
      - name: Log in to Docker Hub
        run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push the Docker image to Docker Hub
        run: docker push dec3ntraliz3d/blog:latest
