name: Terraform Main

on:
  push:
    # paths: '**.tf'
    branches:
      - main
      - reuse_workflow
  pull_request:
    # paths: terraform-main/**
    branches:
      - main
permissions:
  # This is required for requesting the JWT for connecting to aws.
  id-token: write
  contents: read
jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      working_directory : ./terraform-main
    secrets:
      AWS_ROLE_TO_ASSUME : ${{secrets.AWS_ROLE_TO_ASSUME}}
      PUBLIC_KEY : ${{secrets.PUBLIC_KEY}}
