name: Terraform
on:
  workflow_call:
    inputs:
        working_directory:
            type: string
            required: true
    outputs:
        ec2_public_ip:
            description: EC2 public IP address 
            value: ${{jobs.terraform.outputs.ec2-public-ip}}
jobs:
  terraform:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{inputs.working_directory}}  # Set working directory for main
    outputs:
        ec2-public-ip: ${{steps.ec2-public-ip.outputs.ec2-public-ip}}  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        # https://github.com/aws-actions/configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - name: Set public key
        run: echo "TF_VAR_public_key=${{ secrets.PUBLIC_KEY }}" >> $GITHUB_ENV
      - name: Initialize Terraform
        run: terraform init
      - name: Validate Terraform code
        run: terraform validate
      - name: Plan Terraform changes
        run: terraform plan
      - name: Apply Terraform changes
        run: terraform apply -auto-approve
      - name: Output EC2 Public IP
        id: ec2-public-ip
        run: |
          echo "ec2-public-ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT






