name: Update Blog

on:
 workflow_run:
   workflows: [Docker Build]
   types: [completed]
jobs:
  deploy:
    
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get EC2 Public DNS
        uses: actions/download-artifact@v3
        with:
          name: ec2_public_dns
      - name: Put EC2 Public DNS in env variable
        run: |
          echo "ec2_public_dns=$(cat ec2_public_dns.txt)" >> $GITHUB_ENV
      - name: SSH to EC2 and Deploy new docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.ec2_public_dns}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            if [ "$(docker ps -q -f name=blog)" ]; then
              docker stop blog
            fi
            docker rm blog
            docker run -d -p 80:5000 --name "blog" dec3ntraliz3d/blog:latest




